amp: false
rng_seed: 0
num_gpus: 1
out_dir: results
exp_name: cartpole
resume_path: null
test_only: false
debug_mode: false

dataset:
  name: cartpole
  train_metric: train_ret
  path: "checkpoint_datasets/cartpole"
  num_test_runs: 2050
  augment: true
  normalizer: openai
  openai_coeff: 2.06
  target_epoch_size: 806400
  max_train_runs: 1000000
  num_workers: 1

vis:
  freq: 10
  num_nets_per_gpu: 8
  net_mb_size_per_gpu: 8
  recursive_probe: false
  use_ema: true
  dvo_steps: 20
  prompt_start_coeff: 1.0

sampling:
  thresholding: none

transformer:
  ema: true
  absolute_loss_conditioning: true
  predict_xstart: true
  chunk_size: 2048
  split_policy: "layer_by_layer"
  max_freq_log2: 14
  num_frequencies: 128
  n_embd: 1536
  encoder_depth: 1
  decoder_depth: 1
  n_layer: 12
  n_head: 12
  dropout_prob: 0.0

train:
  ema_decay: 0.9999
  beta2: 0.999
  grad_clip: 0.0
  warmup_factor: 0.0
  warmup_epochs: 10
  lr_sch: cos
  base_lr: 2e-4
  wd: 0.1
  num_ep: 2000
  mb_size: 8192
  checkpoint_freq: 500

test:
  freq: 10
  mb_size: 8192
  use_ema: false

wandb:
  name: ${exp_name}
  group: default
  project: Gpt
  entity: learn2learn
  mode: online

defaults:
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .
